CREATE DATABASE TRAVEL_AGENCY;
USE TRAVEL_AGENCY;

CREATE TABLE TRAVEL_AGENT(AGENT_ID INT PRIMARY KEY,NAME VARCHAR(20),EMAIL VARCHAR(25),PHONE_NUMBER INT);

CREATE TABLE PASSENGER(PASSENGER_ID INT PRIMARY KEY,NAME VARCHAR(20),AGE INT,GENDER VARCHAR(7),PASSPORT_NUMBER VARCHAR(10));

CREATE TABLE FLIGHT(FLIGHT_ID INT PRIMARY KEY, AIRLINE_NAME VARCHAR(20), ORIGIN VARCHAR(20), DESTINATION VARCHAR(20), DEPARTURE_TIME DATETIME, ARRIVAL_TIME DATETIME);

CREATE TABLE SEAT(SEAT_ID INT PRIMARY KEY,FLIGHT_ID INT,SEAT_NUMBER VARCHAR(4),CLASS VARCHAR(10),AVAILABILITY INT(3),PRICE INT,FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID));

CREATE TABLE BOOKINGS (BOOKING_ID INT PRIMARY KEY, AGENT_ID INT, FLIGHT_ID INT, BOOKING_DATE DATE, STATUS_ VARCHAR(20), FOREIGN KEY (AGENT_ID) REFERENCES TRAVEL_AGENT(AGENT_ID), FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID));

CREATE TABLE Booking_Passenger (BOOKING_ID INT, PASSENGER_ID INT, SEAT_ID INT, MEAL_PREFERENCE VARCHAR(50),WHEELCHAIR_REQUIRED BOOLEAN, SPECIAL_ASSISTANCE VARCHAR(100), INFANT_BASSINET_REQUIRED BOOLEAN, PRIMARY KEY (BOOKING_ID, PASSENGER_ID), FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID), FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID), FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID));

CREATE TABLE PAYMENT(PAYMENT_ID INT PRIMARY KEY, BOOKING_ID INT, AMOUNT DECIMAL(10,2), PAYMENT_METHOD VARCHAR(20), PAYMENT_DATE DATE,PAYMENT_STATUS VARCHAR(20), FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID));
